Added extended packed desig functionality
NASA-Planetary-Science/sbpy pull request #406
Opened 2024-08-23 02:24 UTC by hhsieh00

Added functionality for extended packed provisional designations to be implemented by the MPC in anticipation of higher discovery rates from LSST (https://minorplanetcenter.net/mpcops/documentation/provisional-designation-definition/)

2024-08-23 02:24 UTC, pep8speaks commented
Hello @hhsieh00! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`sbpy/data/names.py`](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py):

> [Line 73:1](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L73): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 152:1](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L152): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 172:33](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L172): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 172:37](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L172): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 172:41](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L172): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 173:52](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L173): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 236:16](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L236): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 237:16](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L237): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 237:41](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L237): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 238:16](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L238): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 243:22](https://github.com/NASA-Planetary-Science/sbpy/blob/d4eb0cc0efed63f7810a5a827ca75fa58d116b10/sbpy/data/names.py#L243): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2024-08-24 00:02 UTC, mkelley commented
I'll do a detailed review later, but it looks like two of your lines are not covered by the tests:

https://app.codecov.io/gh/NASA-Planetary-Science/sbpy/pull/406/blob/sbpy/data/names.py#L164

Can you add a case that raises IndexError or ValueError?  You can test it like so:

```python
def test_raises_error():
    with pytest.raises(IndexError):
        Names.to_packed("bad_input_here")
```

There are a couple other blocks not in our testing suite, but they don't seem to be related to your edits, so I won't make you cover them.

2024-08-25 00:17 UTC, hhsieh00 commented
Just a note, I think line 140 (which I didn't write, but just put inside a try-except block; but which is currently flagged as uncovered code) is extraneous, since the "s[6:].isdigit()" condition above it should already prevent anything that looks like "1995 A" (i.e., single letter, no subscript) from being passed through that section.  As such, I think it can be deleted, but just wanted to get a second opinion before doing so.

2024-08-26 17:29 UTC, mkelley commented
You're right, except that we can get to that line with a cometary fragment style designation.  I'm seeing two problems. 
 Something like "1234 A-A" returns a value, but should raise an error, right?  Also, lines 129 and 131 test for the hyphen that denotes a fragment.  They test `s[-2]` but fragments could be two characters (73P-BA).  The testing suite doesn't check for two character fragments, but it should.

```
In [3]: Names.to_packed("2024 A-A")
Out[3]: 'K24A00a'
```

They are unrelated, so we should proceed with this PR, and open issues for each of them.

2024-08-26 22:42 UTC, hhsieh00 commented
Oh yeah, I did notice that multi-letter fragments were not accounted for in the code, but also that they do not seem to be accounted for by the MPC's own documentation (https://www.minorplanetcenter.net/iau/info/PackedDes.html), except by making the 7 character packed designation into an 8 character designation since the fragment is simply recorded in plain-text.  And yeah, 1234 A-A seems like a different issue, so maybe better to treat it with a separate issue/PR?

2024-08-26 22:44 UTC, hhsieh00 commented
By the way, just for traceability, in working on the code for the extended packed provisional designations, I found that the MPC had also extended its scheme for packed permanent designations beyond 620000, so code for handling extended packed permanent designations is also included in this PR.

2024-08-27 16:01 UTC, mkelley requested changes
The updates look good.  Since you tagged it v0.6, we will merge after v0.5 is out.

2024-08-27 19:18 UTC, hhsieh00 commented on sbpy/data/names.py
> +                pkd_noI = 'ABCDEFGHJKLMNOPQRSTUVWXYZ'
done!

2024-08-29 20:37 UTC, mkelley approved these changes
You'll need to rebase with the updated main branch, then resolve the changes.rst conflicts.  Let me know if you want some tips.

2024-08-30 18:45 UTC, hhsieh00 commented
Hm, yeah, can you send me info on how to do that?  Thanks!

2024-09-06 21:11 UTC, merged

2024-09-06 22:04 UTC, mkelley commented
Congrats!