identify invalid comet designation with fragment
NASA-Planetary-Science/sbpy pull request #417
Opened 2024-11-09 00:49 UTC by hhsieh00

Added code to check to see if comet designation without a fragment is a valid designation or not (e.g., not passing 2024 A-A when 2024 A is not a valid designation).  Basically just checks to see if the remaining designation without the fragment suffix has enough characters to be turned into a normal packed designation.

2024-11-09 01:10 UTC, hhsieh00 commented
For what it's worth, I didn't use the suggested fix approach listed in the originating issue (removing the fragment designation, parsing the designation using normal rules without the fragment, and adding the fragment back) because it would mean replicating the fragment parsing code in a second location, where invalid non-fragment designations (e.g., 2024 A) fail simply because the string is too short, so it seemed easier to just keep the single instance of the fragment parsing code and just testing the length of the remaining string and raising a failure if it's too short.

2024-11-11 21:18 UTC, mkelley commented
Are two character fragments supported by the standard?  If not, then I'm OK with this approach.

2024-11-11 22:53 UTC, hhsieh00 commented
If by "supported by the standard", you mean that something like 2024 A-AA will also raise a TargetNameParseError, the answer is yes, but for a different reason than the failure of 2024 A-A. 2024 A-A will fail because the remaining designation after stripping the fragment designation (2024 A) is not long enough.  2024 A-AA will raise a TargetNameParseError as well, but because it actually currently would not be recognized as a comet at all.  For comets, the code currently looks for (1) a year + single letter + number OR (2) a single-character fragment at the end of the designation (i.e., a dash + single letter, with no condition on what precedes the fragment designation), so 2024 A-AA will fail both (1) and (2) and pass through to the asteroid designation parsing block.  There, "A-" will be interpreted as the half-month part of the designation, and the remainder of the string "AA" will be interpreted as the asteroid number in that half-month and fail because it's not numeric.

This would be the right outcome for the wrong reason, and could be fixed by initially screening for comets by nesting (2) inside (1) (only testing (2) if (1) passes), rather than the current "or" statement.  I can change the fix to that approach if you prefer.

Otherwise, I think dealing with two character fragments in general runs into [Issue 408](https://github.com/NASA-Planetary-Science/sbpy/issues/408), where two character fragments require the longer packed comet designation format since the 7-character packed comet designation format (which is the only format option in the current code) only has space for a single-character fragment, i.e., 2024 A1-Z will pass, but 2024 A1-AA will fail).  I can work on that first to get this all fixed up before getting into the more involved astorbDB query development.

2024-11-12 00:25 UTC, mkelley requested changes
I think you can go ahead with this, as it solves the main issue.  But I'm thinking there is room for improvement, e.g., we could use the is_comet and is_asteroid tests for code branching, instead of testing precise string indices.

Add something to the changelog and this can be merged.

2024-11-12 14:01 UTC, mkelley approved these changes

2024-11-12 14:01 UTC, merged